general:
steps:
  mtaBuild:
    platform: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    apiEndpoint: 'https://api.cf.ap21.hana.ondemand.com/'
    org: '7d8aaaf2trial'
    space: 'dev'
    username: 'esalacupnamde420@protonmail.com'
    password: '#7*^pgH9Hr75w'