general:
steps:
  mtaBuild:
    platform: 'CF'
  cloudFoundryDeploy:
    DeployTool:'mtaDeployPlugin'
    cfApiEndpoint: 'https://api.cf.ap21.hana.ondemand.com/'
     cfOrg: '7d8aaaf2trial'
     cfSpace: 'dev'
     credentials: 'CF-trial-veeru'
