general:
steps:
  mtaBuild:
    platform: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    apiEndpoint: 'https://api.cf.us10.hana.ondemand.com/'
    org: '7d8aaaf2trial_karna-3retsk7s'
    space: 'karna'
    credentialsId: 'CF-trial-veeru'