general:
steps:
  mtaBuild:
    platform: 'CF'
  cloudFoundryDeploy:
    mtaDeployPlugin:
      dockerImage: 'ppiper/cf-cli:6'
      dockerWorkspace: '/home/piper'
    mta:
      deployTool: 'mtaDeployPlugin'
    cloudFoundry:
      deployTool:'mtaDeployPlugin'
      apiEndpoint: 'https://api.cf.ap21.hana.ondemand.com/'
      org: '7d8aaaf2trial'
      space: 'dev'
      credentialsId: 'CF-trial-veeru'